title = "Jaclyn Brockschmidt"
baseURL = "https://jaclynbrock.com/resume/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Seattle, WA"
email = "jcbrockschmidt@gmail.com"
favicon = "favicon.ico"
firstName = "Jaclyn"
lastName = "Brockschmidt"
#phone = "1-555-555-1234"
jobTitle = "Software Developer"
profileImage = "img/profile-pic.jpg"
showEducation = true
showExperience = true
showOpenSource = true
showProjects = true
showResearch = true
showQr = true
showSkills = true

# [params.google]
# [params.google.analytics]
# trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/jcbrockschmidt/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/jcbrockschmidt/"
name = "GitHub"

# [[params.handles]]
# link = "https://stackoverflow.com/users/story/82880"
# name = "Stack Overflow"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"